// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8bPkyFtn03qalzuTtUaMOqBzwIKZwqY',
    appId: '1:216825408617:web:5b31a826a72daf447b86f8',
    messagingSenderId: '216825408617',
    projectId: 'sendsms-23ddd',
    authDomain: 'sendsms-23ddd.firebaseapp.com',
    storageBucket: 'sendsms-23ddd.appspot.com',
    measurementId: 'G-6NPCYPZN8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxXWSxzXU3i2no80ULkLTP3t7B1AnPOJ0',
    appId: '1:216825408617:android:d9485aac5a0a1bfe7b86f8',
    messagingSenderId: '216825408617',
    projectId: 'sendsms-23ddd',
    storageBucket: 'sendsms-23ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUE0-H7uEpcDr9o00DoWKn2hjIy2v1UAQ',
    appId: '1:216825408617:ios:a463496da0823adf7b86f8',
    messagingSenderId: '216825408617',
    projectId: 'sendsms-23ddd',
    storageBucket: 'sendsms-23ddd.appspot.com',
    iosBundleId: 'com.example.sendSmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUE0-H7uEpcDr9o00DoWKn2hjIy2v1UAQ',
    appId: '1:216825408617:ios:b2902ae2102a576b7b86f8',
    messagingSenderId: '216825408617',
    projectId: 'sendsms-23ddd',
    storageBucket: 'sendsms-23ddd.appspot.com',
    iosBundleId: 'com.example.sendSmsApp.RunnerTests',
  );
}
